#config_version=5

mode:
  priority: 500
  start_events: game_ending
  stop_events: high_score_enter_initials_completed
  use_wait_queue: true

high_score:
  enter_initials_timeout: 30s
  award_slide_display_time: 4s
  categories:
    !!omap
    - score:
      - GRAND CHAMPION
      - HIGH SCORE 1
      - HIGH SCORE 2
      - HIGH SCORE 3
  defaults:
    score:
      - ZUK: 500000
      - DOG: 250000
      - AMY: 100000
      - GOO: 50000
