#config_version=5

mode:
  priority: 500
  start_events: game_ending, start_high_score
  stop_events: high_score_enter_initials_completed
  use_wait_queue: true

# optional: change the slides (you can omit all the following)
slide_player:
  _overwrite: True
  high_score_enter_initials: high_score_enter_initials

slides:
  high_score_enter_initials:
    widgets:
      - type: image
        image: Amigos_billboard  # Using the image you already defined
      - type: text
        text: "A NEW HERO EMERGES!"
        y: 80%
        font_size: 90
        color: yellow
      - type: text
        text: "SANTO POCO"  # Added some Amigos flavor
        y: 85%
        font_size: 100        # Much larger
        color: red
        font_name: WESTERN_LIGHT
      - type: text
        text: (award)
        y: 65%
        font_size: 60
        color: white
        font_name: WESTERN_LIGHT
      - type: text
        text: (player_name)
        y: 40%
        font_size: 250        # Massive initials for that hero moment
        color: yellow
        font_name: WESTERN_LIGHT
      - type: text
        text: "USE FLIPPERS TO SELECT - START TO ENTER"
        y: 10%
        font_size: 30
        color: gray

high_score:
  _overwrite: True
  enter_initials_timeout: 30s
  award_slide_display_time: 4s
  categories:
    !!omap
    - score:
      - GRAND CHAMPION
      - HIGH SCORE 1
      - HIGH SCORE 2
      - HIGH SCORE 3
  defaults:
    score:
      - ZUK: 500000
      - DOG: 250000
      - AMY: 100000
      - GOO: 50000
