#config_version=5

mode:
  priority: 500
  start_events: game_ending
  stop_events: high_score_enter_initials_completed

high_score:
  categories:
    score:
      - GRAND CHAMPION
      - HIGH SCORE 1
      - HIGH SCORE 2
      - HIGH SCORE 3
  # Move settings back to the top level, but check the indentation
  config:
    enter_initials_timeout: 30s
    chars: ABCDEFGHIJKLMNOPQRSTUVWXYZ.- 
    shift_left_tag: left_flipper
    shift_right_tag: right_flipper
    select_tag: start
