#config_version=5

high_score:
  award_names:
    - Grand Champion
    - High Score 1
    - High Score 2
  categories:
    score:
      - Grand Champion
      - High Score 1
      - High Score 2
  defaults:
    score:
      Grand Champion: 1000
      High Score 1: 500
      High Score 2: 250