#config_version=5

mode:
  priority: 500
  start_events: game_ending, start_high_score
  use_wait_queue: true

high_score:
  _overwrite: True
  enter_initials_timeout: 60
  award_slide_display_time: 4s

  # define your high score categories and the awards
  categories: !!omap
  - score:
      - El Amigo Supremo
      - The First Amigo
      - The Second Amigo
      - The Third Amigo
      - Amigo in training
  - loops:
      - LOOP CHAMP
  - completed_spins:
      - SPIN CHAMP

  # set the defaults
  defaults:
    score:
      - MPF: 10
      - BRI: 9
      - JAN: 8
      - QUI: 7
      - MAR: 6
    loops:
      - JAN: 1
    completed_spins:
      - COO: 1

#sound_player:
  #high_score_enter_initials:
    #song_enter_initials:
      #action: play
      #loops: 0

# optional: change the slides (you can omit all the following)
slide_player:
  _overwrite: True
  high_score_enter_initials: high_score_enter_initials
  high_score_award_display: high_score_award_display

slides:
  _overwrite: True
  high_score_enter_initials:
  - type: text
    # style: tall_title
    font_size: 50
    text: AMIGO (player_num)
    color: ffff00
    anchor_x: left
    anchor_y: bottom
    x: left+50
    y: bottom+200
    # x: 105
    # y: 90

  - type: text
    # style: tall_title
    font_size: 50
    text: (award)
    color: f0f0f0
    anchor_x: left
    anchor_y: bottom
    x: left+50
    y: bottom+140
    # x: 105
    # y: 70

  - type: text_input
    initial_char: A
    dynamic_x: false
    key: high_score
    # style: tall_title
    font_size: 50
    max_chars: 3
    anchor_x: left
    anchor_y: bottom
    x: left+100
    y: bottom+80
    # x: 105
    # y: 20
    shift_left_event: s_left_flipper_active
    shift_right_event: s_right_flipper_active
    select_event: s_start_active
    color: ff0000

  - type: text
    # style: tall_title
    text: '<       >'
    font_size: 50
    anchor_x: left
    anchor_y: bottom
    x: left+50
    y: bottom+80
    # x: 105
    # y: 20
    color: ff0000


  - type: text
    text: ''
    key: high_score
    font_size: 50
    x: left+120
    y: bottom+50
    # style: tall_title
    color: ff00ff
    animations:
      show_slide:
      - property: opacity
        value: 1
        duration: 0.3s
        easing: in_out_quint
      - property: opacity
        value: 0
        duration: 0.3s
        repeat: true
        easing: in_out_quint

  high_score_award_display:
  - type: text
    text: (player_name)
    font_size: 50
    # style: tall_title
    anchor_y: middle
    anchor_x: middle
    x: middle
    y: middle
    color: 00ff00
    animations:
      show_slide:
      - property: opacity
        value: 1
        duration: 0.05s
      - property: opacity
        value: 0
        duration: 0.05s
        repeat: true
  - type: text
    text: (award)
    font_size: 50
    anchor_y: middle
    anchor_x: middle
    x: middle
    y: middle+75
    # style: tall_title
    color: 0000ff
  - type: text
    text: (value)
    anchor_y: middle
    anchor_x: middle
    x: middle
    y: middle+150
    # style: tall_title
    color: 4040FF
    font_size: 125
    number_grouping: true
    min_digits: 1
