#config_version=5
##! show: attract_display_loop
#! - duration: .1
#!   events: ok_super
##! mode: attract
mode:
  stop_events: game_start

show_player:
  mode_attract_started: attract_display_loop

sound_player:
  mode_attract_started:
    song_attract:
      action: play
      loops: -1

  mode_attract_stopped:
    music:
      action: stop
