#config_version=5
mode:
  start_events: ball_starting
  stop_events: game_ended
  priority: 100

variable_player:
  s_spinner_active:
    score: 5
  s_L_circle_active:
    score: 50
  s_C_CaptiveStanding_active:
    score: 10
  s_L_RightRamp_active:
    score: 10
  s_R_RightRamp_active:
    score: 10
  s_right_jet_active:
    score: 5
  s_drop_target_left_active:
    score: 5
  s_drop_target_middle_active:
    score: 5
  s_drop_target_right_active:
    score: 5
  drop_target_bank_dt_bank_down:
    score: 50

slides:
  # Rename this slightly to ensure no conflicts with other modes
  mode_base_bank_cleared:
    widgets:
      - type: text
        text: BANK CLEARED!
        font_size: 80
        color: green
      - type: text
        text: "+50 POINTS"  # Added quotes for safety
        y: 30%
        font_size: 40
  skill_success_slide:
    widgets:
      - type: video
        video: skill
        end_behavior: stop
    expire: 2s

sound_player:
  mode_base_started:
    song_01:
      action: play
      #loops: -1  
  s_spinner_active:
    sfx_spinner_sew:
      action: play
      loops: 0
  s_L_circle_active:
    voice_very_great:
      action: play
      loops: 0
  drop_target_bank_dt_bank_down:
    voice_real_bullets:
      action: play
      loops: 0
  s_L_RightRamp_active:
    sfx_pot_crash:
      action: play
      loops: 0
  s_R_RightRamp_active:
    sfx_pot_crash:
      action: play
      loops: 0
  s_C_CaptiveStanding_active:
    sfx_gunshot:
      action: play
      loops: 0
  s_right_jet_active:
    sfx_gunshot:
      action: play
      loops: 0


slide_player:
  drop_target_bank_dt_bank_down:
    mode_base_bank_cleared:
      target: window      # Explicitly tell it where to go
      expire: 5s
      priority: 1000      # Make it high to "overrule" everything
    skill_success_slide:
      target: window      # Explicitly tell it where to go
      expire: 3s
      priority: 1001      # Make it high to "overrule" everything
