#config_version=5

hardware:
    platform: p3_roc
#    platform: smart_virtual #mpf both -X to run virtual platform now

p_roc:
  driverboards: pdb
  use_watchdog: true
  watchdog_time: 1s

modes:
  - base
  - high_score

config:
- hardware.yaml
- keyboard.yaml

# This ensures the game knows where to look for your Western assets
paths:
  fonts: fonts
  images: images
