#config_version=5

hardware:
  platform: p3_roc
#    platform: smart_virtual #mpf both -X to run virtual platform now

p_roc:
  driverboards: pdb
  use_watchdog: true
  watchdog_time: 1s

config:
  - hardware.yaml
  - keyboard.yaml
  - sounds.yaml

modes:
  - base
  - high_score

slides:
  welcome_slide:
    widgets:
      - type: text
        text: PINBALL!
        font_size: 50
        color: red
      - type: rectangle
        width: 240
        height: 60

slide_player:
  init_done: welcome_slide
