#config_version=5

widget_styles:
  base_score_display:
    number_grouping: true
    min_digits: 2
    font_size: 100
    #font_name: WoodenNickelNF
  base_ball_display:
    font_size: 50
    #font_name: Sho-CardCapsNF
    anchor_y: bottom
    y: bottom+50
  base_player1_display:
    number_grouping: true
    min_digits: 2
    font_size: 35
    #font_name: bell
    anchor_x: left
    anchor_y: top
    x: left+50
    y: top-50
  base_player2_display:
    number_grouping: true
    min_digits: 2
    font_size: 35
    #font_name: bell
    anchor_x: right
    anchor_y: top
    x: right-50
    y: top-50
  base_player3_display:
    number_grouping: true
    min_digits: 2
    font_size: 35
    #font_name: bell
    anchor_x: left
    anchor_y: bottom
    x: left+50
    y: bottom+50
  base_player4_display:
    number_grouping: true
    min_digits: 2
    font_size: 35
    #font_name: bell
    anchor_x: right
    anchor_y: bottom
    x: right-50
    y: bottom+50
